import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import "./app.css";
//import "./style.css"
import Navbar from "../app/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fotio",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        {children}
          
      </body>
    </html>
  );
}
